-- CREATE TABLE-- CREATE TABLE

CREATE TABLE IF NOT EXISTS membros(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome text NOT NULL,
    telefone integer NOT NULL,
    email text NOT NULL,
    endereco text,
    situacao text NOT NULL,
    datahoraactual date,
    datsahoracriacao date
);

CREATE TABLE IF NOT EXISTS tipos(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    descricao text NOT NULL,
    situacao text NOT NULL,
    datahoraactual date,
    datahoracriacao date,
    membroid INTEGER REFERENCES membros(id)
);
